notejam:
  image:
    repository: 441604169807.dkr.ecr.eu-west-1.amazonaws.com/notejam
    tag: f9ce35a556d3f9509c38ad21c41aef842724a83b
  deploy:
    ## Application properties file for configuring the Quarkus app
    applicationProperties:
      ## Determines if application properties should be created in a configmap and mounted to the Quarkus container
      enabled: true
      ## Location to mount the properties file
      mountPath: /deployments/config/
      ## Application properties file contents
      properties: |-
        ## Properties go here
        email.sender: Markus Malkusch <markus@malkusch.de>
        ; If you want to have mail transport, configure at least the property spring.mail.host,
        ; otherwise mail transport is not available.
        ; For further mail configuration see http://docs.spring.io/spring-boot/docs/current/api/index.html?org/springframework/boot/autoconfigure/mail/MailProperties.html
        ;
        ;spring.mail.host: smtp.example.net
        spring.jpa.hibernate.ddl-auto=update
        async.queueCapacity: 1000
        ; ISO 8601 period until a recovery token expires.
        recovery.lifetime: P1D
        ; The length of the generated password.
        recovery.length: 32
        spring.datasource.username=notejam
        spring.datasource.password=notejamnotejam
        spring.datasource.driver-class-name=com.mysql.jdbc.Driver
        spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
        spring.datasource.url=jdbc:mysql://nc-demo.clem8lnaphpu.eu-west-1.rds.amazonaws.com:3306/notejam
