notejam:
  image:
    repository: 441604169807.dkr.ecr.eu-west-1.amazonaws.com/notejam
    tag: 91753f67df21ee926d43b79a2f8110f0cacfa9d3
  deploy:
    ## Application properties file for configuring the Quarkus app
    applicationProperties:
      ## Determines if application properties should be created in a configmap and mounted to the Quarkus container
      enabled: true
      ## Location to mount the properties file
      mountPath: /deployments/config/
      ## Application properties file contents
      properties: |-
        ## Properties go here
        email.sender: Markus Malkusch <markus@malkusch.de>
        ; If you want to have mail transport, configure at least the property spring.mail.host,
        ; otherwise mail transport is not available.
        ; For further mail configuration see http://docs.spring.io/spring-boot/docs/current/api/index.html?org/springframework/boot/autoconfigure/mail/MailProperties.html
        ;
        ;spring.mail.host: smtp.example.net
        spring.jpa.hibernate.ddl-auto=update
        async.queueCapacity: 1000
        ; ISO 8601 period until a recovery token expires.
        recovery.lifetime: P1D
        ; The length of the generated password.
        recovery.length: 32
        spring.datasource.username=notejam
        spring.datasource.password=${DB_PASS}
        spring.datasource.driver-class-name=com.mysql.jdbc.Driver
        spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
        spring.datasource.url=jdbc:mysql://${DB_HOSTNAME}:3306/notejam